# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - serverapi

on:
  push:
    branches:
      - fpt/deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://serverapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bcbd60fc0021497d8b870a5a950ce4a4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b56244e33b804c4080ba1d3dab154af6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: serverapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bcbd60fc0021497d8b870a5a950ce4a4 }}/server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'serverapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_452bfccf514a486b90cc2627de59af9f }}
        images: 'serverapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bcbd60fc0021497d8b870a5a950ce4a4 }}/server:${{ github.sha }}'