name: Deploy Multiple APIs to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Debug - List all files
        run: ls -R

      - name: Build & Publish Backend
        run: |
          cd Backend
          ls -R  # Debug: Liệt kê toàn bộ file để kiểm tra
          dotnet restore Blind-Bag-ECommerce.sln  # Restore toàn bộ project
          dotnet publish Auth/Auth.csproj -c Release -r linux-x64 --self-contained false -o ../backend/Auth
          dotnet publish Client/Client.csproj -c Release -r linux-x64 --self-contained false -o ../backend/Client

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifacts
          path: backend/

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-artifacts
          path: backend/  # Đảm bảo tải về đúng thư mục

      - name: Debug - List downloaded files
        run: ls -R backend/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy Client API vào thư mục /client (chữ thường)
      - name: Deploy Client API
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'swd392-sp25'
          package: 'backend/client'  # Sửa đường dẫn để khớp với thư mục tải về
          slot-name: 'Production'

      # Deploy Auth API vào thư mục /auth (chữ thường)
      - name: Deploy Auth API
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'swd392-sp25'
          package: 'backend/auth'  # Sửa đường dẫn để khớp với thư mục tải về
          slot-name: 'Production'
