name: Build and deploy ASP.Net Core app to Azure Web App - Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Build cả 2 project
      - name: Build Auth API
        run: dotnet build Backend/Auth -c Release

      - name: Build Client API
        run: dotnet build Backend/Client -c Release

      # Publish cả 2 project
      - name: Publish Auth API
        run: dotnet publish Backend/Auth -c Release -o "${{env.DOTNET_ROOT}}/auth"

      - name: Publish Client API
        run: dotnet publish Backend/Client -c Release -o "${{env.DOTNET_ROOT}}/client"

      # Upload artifact cho quá trình deploy
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifacts
          path: |
            ${{env.DOTNET_ROOT}}/auth
            ${{env.DOTNET_ROOT}}/client

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-artifacts

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy Client API lên App Service Client
      - name: Deploy Client API
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'client-api-app-name'
          slot-name: 'Production'
          package: './client'

      # Deploy Auth API lên App Service Auth
      - name: Deploy Auth API
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'auth-api-app-name'
          slot-name: 'Production'
          package: './auth'
